### ISSUE TITLE
User can turn their car

### ISSUE THREAD

**Issue by qnpham** [qnpham/driving-game#2]
## 💰 Motivation

The user needs to be able to control which way their car is facing.

## 📐 Plan

Rotate the image with CSS classes when the user presses an arrow key.

## ✅ Task List

- [x] make classes for rotating
- [x] add an event listener to document
- [x] on click if key is right arrow then apply turn right class, if key is left arrow then apply left turn class.
- [x] make a data model to know which direction the car is faced
- [x] ensure that each turn is repeatable and the car can turn multiple times
- [x] add a transition to car so the turns are smooth and animated
