### ISSUE TITLE
User can start their car

### ISSUE THREAD

**Issue by qnpham** [qnpham/driving-game#3]
## 💰 Motivation

It's a driving game, duh!

## 📐 Plan

Move the car a few pixels every 16 milliseconds when the user presses space.

## ✅ Task List

- [x] make the car position relative
- [x] listen for space
- [x] make a function to move the car a few pixels
- [x] when the user presses space call the function every 16 milliseconds
