### ISSUE TITLE
User can stop their car

### ISSUE THREAD

**Issue by qnpham** [qnpham/driving-game#4]
## 💰 Motivation

If the user cannot stop their car, it goes off the page.

## 📐 Plan

Stop the car if the user presses space again.

## ✅ Task List

- [x] add a boolean to data model.
- [x] make every time space is pressed, the opposite value of the boolean is set to boolean.
- [x] if boolean is true when pressing space, then stop the interval and set the boolean to equal false.
